variable "resource_group_name" {
  type = string
}

variable "system_abbreviation" {
  type = string
}

variable "environment_abbreviation" {
  type = string
}

variable "instance_number" {
  type = string
}

variable "workload_description" {
  type    = string
  default = ""
}

variable "location" {
  type = string
}

variable "config" {
  type = object({
    afdPeAutoApproverIsolationScope = string
    managedIdentities = object({
      systemAssigned = bool
    })
    enableDefaultWafMethodBlock = bool
    wafCustomRules = object({
      rules = optional(list(object({
        name                       = string
        action                     = string
        enabledState               = optional(string)
        priority                   = number
        ruleType                   = optional(string)
        type                       = optional(string)
        rateLimitDurationInMinutes = optional(number)
        rateLimitThreshold         = optional(number)
        matchConditions = optional(list(object({
          matchVariable      = optional(string)
          match_variable     = optional(string)
          operator           = string
          negateCondition    = optional(bool)
          negation_condition = optional(bool)
          matchValue         = optional(list(string))
          match_values       = optional(list(string))
          selector           = optional(string)
          transforms         = optional(list(string))
        })), [])
        conditions = optional(list(object({
          match_variable     = string
          operator           = string
          negation_condition = optional(bool)
          match_values       = optional(list(string))
        })), [])
      })), [])
    })
    customDomains = list(any)
    ruleSets      = list(any)
    secrets       = list(any)
    roleAssignments = optional(list(object({
      key                                = optional(string)
      roleDefinitionId                   = optional(string)
      roleDefinitionName                 = optional(string)
      principalId                        = string
      principalType                      = optional(string)
      description                        = optional(string)
      condition                          = optional(string)
      conditionVersion                   = optional(string)
      delegatedManagedIdentityResourceId = optional(string)
      name                               = optional(string)
    })), [])
    originResponseTimeoutSeconds = number
    autoApprovePrivateEndpoint   = bool
    sku                          = string
    wafPolicySettings = object({
      enabledState     = string
      mode             = string
      requestBodyCheck = string
    })
    wafManagedRuleSets = list(object({
      ruleSetType        = string
      ruleSetVersion     = string
      ruleSetAction      = optional(string)
      ruleGroupOverrides = optional(list(any), [])
    }))
    originGroups = list(object({
      name           = string
      authentication = optional(any)
      healthProbeSettings = optional(object({
        probePath              = optional(string)
        probeIntervalInSeconds = optional(number)
        probeRequestType       = optional(string)
        probeProtocol          = optional(string)
      }))
      loadBalancingSettings = object({
        sampleSize                      = number
        successfulSamplesRequired       = number
        additionalLatencyInMilliseconds = optional(number)
      })
      sessionAffinityState                                  = string
      trafficRestorationTimeToHealedOrNewEndpointsInMinutes = number
      origins = list(object({
        name                        = string
        enabledState                = string
        enforceCertificateNameCheck = bool
        httpPort                    = number
        httpsPort                   = number
        priority                    = number
        weight                      = number
        sharedPrivateLink = optional(object({
          requestMessage = string
          groupId        = string
        }))
      }))
    }))
    afdEndpoints = list(object({
      name = string
      routes = list(object({
        name                = string
        cacheConfiguration  = optional(any)
        customDomainNames   = optional(list(string))
        enabledState        = string
        forwardingProtocol  = string
        httpsRedirect       = string
        linkToDefaultDomain = string
        originGroupName     = string
        originPath          = optional(string)
        patternsToMatch     = list(string)
        ruleSets            = optional(list(string))
        supportedProtocols  = list(string)
      }))
      tags                              = optional(map(string))
      autoGeneratedDomainNameLabelScope = string
      enabledState                      = string
    }))
    securityPatternsToMatch = optional(list(string), ["/*"])
    lock = optional(object({
      kind  = string
      name  = optional(string)
      notes = optional(string)
    }))
    diagnosticSettings = optional(list(object({
      name                                = optional(string)
      workspaceResourceId                 = optional(string)
      logAnalyticsDestinationType         = optional(string)
      storageAccountResourceId            = optional(string)
      eventHubAuthorizationRuleResourceId = optional(string)
      eventHubName                        = optional(string)
      marketplacePartnerResourceId        = optional(string)
      logCategoriesAndGroups = optional(list(object({
        category      = optional(string)
        categoryGroup = optional(string)
      })), [])
      metricCategories = optional(list(object({
        category = string
        enabled  = optional(bool)
      })), [])
    })), [])
  })
}

variable "workload_origin_host_name" {
  type = string
}

variable "workload_origin_resource_id" {
  type = string
}

variable "workload_origin_location" {
  type = string
}

variable "tags" {
  type    = map(string)
  default = {}
}
