name: Terraform Azure Deploy

on:
  workflow_dispatch:

env:
  TF_VERSION: 1.11.4
  # Terraform Azurerm provider via OIDC (no secrets)
  ARM_USE_OIDC: true
  ARM_CLIENT_ID:        ${{ secrets.AZURE_CLIENT_ID }}
  ARM_TENANT_ID:        ${{ secrets.AZURE_TENANT_ID }}
  ARM_SUBSCRIPTION_ID:  ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  # Backend (adjust these for your state)
  TF_BACKEND_RG:         akhealth-ies-terraform-tf
  TF_BACKEND_STORAGE:    tfstfef5519ba84acf90f6f7
  TF_BACKEND_CONTAINER:  backends
  TF_BACKEND_KEY:        private/main.tfstate


jobs:
  tf:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - uses: azure/login@v2
        with:
          client-id:       ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:       ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: terraform init (azurerm backend)
        run: |
          terraform init \
            -backend-config="resource_group_name=${TF_BACKEND_RG}" \
            -backend-config="storage_account_name=${TF_BACKEND_STORAGE}" \
            -backend-config="container_name=${TF_BACKEND_CONTAINER}" \
            -backend-config="key=${TF_BACKEND_KEY}" \
            -backend-config="use_azuread_auth=true"

      - name: terraform plan
        run: terraform plan